### ISSUE TITLE
Stopped Application memory 

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry-community/cf_exporter#11]
Hi @frodenas,

It could be nice to add the applications stated somehow, because now stopped application are counted as consuming the quota which I think it's not correct.

Most of my org are over quota because their have 20 or 100 stopped apps.

Thanks

**Comment by frodenas** [comment]
@shinji62 The `cf_application_info` metric has already a `state` label, is this what you are looking for? or do you need any additional info?

**Comment by shinji62** [comment]
Sorry Ferdy, I think my question was not enough clear, in fact the dashboard like cf_organization_memory_quotas.json include stopped application in the calculation of quota usage.

Maybe this is expected, but I was just wondering, it's difficult to check when you org is running of quota when all of them are +100% and so on.

**Comment by mkuratczyk** [comment]
Can you test this dashboard from my fork @shinji62 please (https://github.com/mkuratczyk/prometheus-boshrelease/blob/master/src/cloudfoundry_dashboards/cf_organization_memory_quotas.json) and verify it works for you? Of course I'll submit a PR if it does.

**Comment by frodenas** [comment]
@shinji62 I've merged @mkuratczyk PR, please let me know if this fixes your issue.

**Comment by shinji62** [comment]
Thanks PR resolve my issue. 
Thanks @mkuratczyk
