### ISSUE TITLE
cf_exporter compatible CAPI Version

### ISSUE THREAD

**Issue by mjsjinsu** [cloudfoundry-community/cf_exporter#13]
Can I ask you cf_exporter support CAPI Version?

I think there are many changes since CAPI Version 1.12 on /v2/events API
http://apidocs.cloudfoundry.org/251/events/list_all_events.html
http://apidocs.cloudfoundry.org/247/events/list_all_events.html

In my env has two cloudfoundry deployments
1) cf-release 251 (Contains CAPI release v1.15.0) 
2) cf-release 247 (Contains CAPI release v1.11.0) 

In the 251 environment, application events seem to have problems collecting
and additional app event logs are not collected
The number of apps and users running is almost the same

cf-251
![251](https://cloud.githubusercontent.com/assets/4901749/24794695/8953422a-1bc1-11e7-84ee-eecdc7268f02.PNG)

cf-247
![247](https://cloud.githubusercontent.com/assets/4901749/24794705/8e4b9354-1bc1-11e7-9dfd-75a6819d2f13.PNG)

**Comment by mjsjinsu** [comment]
https://github.com/cloudfoundry/capi-release/issues/46

See above issue

I found cause of issue collecting event problem  

https://github.com/cloudfoundry-community/go-cfclient/blob/master/appevents.go#L144

With CAPI release v1.15.0
"next_url" parameter not working.
Only some logs could collected per event type, because default value is 50(results-per-page parameter) 

There is problem from 2 pages events log or more
$ cf curl  "/v2/events?order-by=timestamp&order-by=id&order-direction=asc&page=2&results-per-page=50"
{
   "code": 10012,
   "description": "Cannot order by: id",
   "error_code": "CF-OrderByParameterInvalid"
}

Can you check this issue?

**Comment by frodenas** [comment]
This exporter uses the `go-cfclient` to gather data from the CF API. Let's fix the `go-cfclient` library first and then I can update the exporter with the latest library version. Let's track the progress at https://github.com/cloudfoundry-community/go-cfclient/issues/99.

**Comment by mjsjinsu** [comment]
https://github.com/cloudfoundry/capi-release/releases/tag/1.26.0

In cf-257 
Resolved issue with /v2/events next_url containing an invalid next page
