### ISSUE TITLE
Is there crashed app health check?

### ISSUE THREAD

**Issue by mjsjinsu** [cloudfoundry-community/cf_exporter#14]
Is it available checking whether the app crashes or down through cf_exporter ??

Currently the information of application health collected through cf_exporter is the cumulative value of the /v2/events API

Whether it is possible to check status instead of cumulative value
I am trying to integration with grafana 

As an example, I can check through the application's stat API as shown below
It would be better to use cf_exporter than to implement blackbox exporter or pushgateway

$ cf curl /v2/apps/34195caa-eaff-4d22-bd31-435f9b6d620d/stats
`
{
   "0": {
      "state": "CRASHED",
      "stats": {
         "name": "spring-music",
         "uris": [
            "spring-music-apophonic-plebeianisation.paasta.ghama.io"
         ],
         "host": null,
         "port": null,
         "uptime": 0,
         "mem_quota": 536870912,
         "disk_quota": 1073741824,
         "fds_quota": 16384,
         "usage": {
            "time": "2017-04-24T10:23:00.414135746Z",
            "cpu": 0,
            "mem": 0,
            "disk": 0
         }
      }
   }
}
`

**Comment by frodenas** [comment]
@mjsjinsu That kind of info are events, not really metrics, and the prometheus model doesn't support it very well. The way that this exporter works is collecting the latest info from the CF API when the prometheus server scrapes it. That means that we can only send the latest info about each metric (ie, we cannot send 2 events of the same type for the same app), this is why this collector just aggregates the info.
