### ISSUE TITLE
Reporting number of app instances running (and desired)

### ISSUE THREAD

**Issue by jriguera** [cloudfoundry-community/cf_exporter#15]
I think in the application_info metric, `cf_exporter` could provide the number of instances running (and the number of instances desired). An application can be in `state=STARTED` but with 0 instances running, which means a crashed app. This metric it could be used to build dashboards to show users these cases of apps crashed (for a long time) allowing them to do some maintenance or clean them up.

For example, this is a metric reported by `cf_exporter` of a crashed app:
```
cf_application_info{application_id="53f291c0-edd9-448d-b7b1-5cb90bf7bb59",application_name="testcloudmoma",buildpack="",deployment="dev",environment="dev",organization_id="19805aa5-2b47-4efd-a688-6a678e9773ce",organization_name="test",space_id="267b182a-c911-4d92-8cbb-5f30b9743d72",space_name="dev",stack_id="7c5b664c-e9b8-457b-83a4-6092b7372494",state="STARTED"} 1
```

App state reported by CF client:
```
$ cf apps | grep test
testcloudmoma                                         started           0/2         256M     1G     testcloudmoma.dev.cf.springer-sbm.com

$ cf app testcloudmoma
Showing health and status for app testcloudmoma in org test / space dev as admin...
OK
requested state: started
instances: 0/2
usage: 256M x 2 instances
urls: testcloudmoma.dev.cf.springer-sbm.com
last uploaded: Tue Jan 3 11:26:45 UTC 2017
stack: cflinuxfs2
buildpack: ruby 1.6.20
     state     since                    cpu    memory      disk      details
#0   crashed   2017-01-05 04:32:44 PM   0.0%   0 of 256M   0 of 1G
#1   crashed   2017-01-05 04:32:13 PM   0.0%   0 of 256M   0 of 1G
```
So the app has 0/2 instances running and nobody is taking care of it

I was thinking, that maybe an acceptable solution is converting the constant value of 1 reported by the metric in the current number of instances running, like this:
```
cf_application_info{application_id="53f291c0-edd9-448d-b7b1-5cb90bf7bb59",application_name="testcloudmoma",buildpack="",deployment="dev",environment="dev",organization_id="19805aa5-2b47-4efd-a688-6a678e9773ce",organization_name="test",space_id="267b182a-c911-4d92-8cbb-5f30b9743d72",space_name="dev",stack_id="7c5b664c-e9b8-457b-83a4-6092b7372494",state="STARTED"} 0
```
so the app is STARTED but with 0 instances running, which means it is crashed. I think this solution makes easy to find such cases. Also, an additional tag to show the "number of desired" instances will help operators to report those things.

What you do think about this?

I know this info can be extracted from events, but in our case we have such a large amount of events than the exporter cannot get them on time (application event scrape duration is more than 10 minutes!).

**Comment by frodenas** [comment]
@jriguera It's a valid use case. The problem I see, regardless of where we report this metric, is how to efficiently retrieve the application instance's status. 

We can get that metric from the [/v2/apps/:guid/summary](https://apidocs.cloudfoundry.org/258/apps/get_app_summary.html) or from the [/v2/apps/:guid/instances](https://apidocs.cloudfoundry.org/258/apps/get_the_instance_information_for_a_started_app.html) API endpoints, but in both cases that means querying the API for each application. We have deployments with > 25k applications, if we implement this, I'm unsure about the collector performance and the pressure we will put on the CC. Thoughts?

w/r/t `AppEvents`, yep, I tend to disable this collector on my deployments, and I'm also thinking about removing it, as I'm unsure that the info being actually reporter is usefull or not.

**Comment by jriguera** [comment]
I know the issue regarding the amount of queries generated with this call. We have an app to minimize the API workload: https://github.com/SpringerPE/cf-light-api, but, ofc it is not suitable for monitoring, because of the caching.

What about [listing all apps by space with /v2/spaces/:guid/apps](https://apidocs.cloudfoundry.org/258/spaces/list_all_apps_for_the_space.html)?. It seems there are the `instances` and `state` parameters, `instances` could be reported directly ...  Anyway, I am not sure if this API call will help us, maybe it is worth doing some tests. What do you think?

Regarding `AppEvents`, we think it is unmanageable in large environments, maybe in small deployments is fine, but in our case we cannot make use of it.

**Comment by jccarte** [comment]
I am not sure of the performance implications, but I have a similar need to determine running vs desired apps and added a metric called applicationRunningInstancesMetric, pulling the information from the space summary. This maybe be too tasking on a large installation though. https://github.com/cloudfoundry-community/cf_exporter/compare/master...jccarte:running_instances?expand=1

**Comment by frodenas** [comment]
Thanks @jccarte. I refactored a bit your code at https://github.com/cloudfoundry-community/cf_exporter/commit/de09e7db80ab54b5ba2fa3c7461086cae361e2fb. On my tests, there's a bit overhead (ms, < 1 sec), but I still need to run more tests to see the performance impact on a high load environment.

@jriguera @jccarte if you want to test it, you can build manually the exporter from master or run the [cfcommunity/cf-exporter:master](https://hub.docker.com/r/cfcommunity/cf-exporter/tags/) Docker image.

**Comment by frodenas** [comment]
`cf_exporter` [v0.5.1](https://github.com/cloudfoundry-community/cf_exporter/releases/tag/v0.5.1) includes the `application_instances_running` metric.
