### ISSUE TITLE
App events collector is very slow

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/cf_exporter#16]
I might be misunderstanding, but it looks like the app events collector fetches all app events every time the exporter is polled. Even on our staging environment, that means fetching >6000 pages of app events, which would take hours to run. Are folks using this collector in production? If so, what settings would make it usable? Or is it acceptable if a request to /metrics takes hours? If not, would it make sense to restrict the query by time range so that it runs faster?

**Comment by jmcarp** [comment]
A few more questions:
* Since capi only retains a certain number of days worth of app events, the app event count can rise and fall over time. Should this metric be a gauge instead of a counter?
* It looks like we're only reporting on the total number of app events. Could we grab the `total_results` field instead of paging through all results? Or are there more metrics planned here that would require fetching all events?

cc @dlapiduz

**Comment by frodenas** [comment]
@jmcarp 

* We don't usually enable it on our prod environments. We ran some experiments on a 20k app environment, and it took about 34mins to scrape all app events.  But it's not about the time what really concerns me, it's the stress it puts on the CC. There is more info at this [blog post](https://www.starkandwayne.com/blog/cloud-controller-reporting-api-server/).
* The `application_events` metric should have never been a `counter`, it should have been a `gauge` like all other `total` metrics, it's a bug.
* The problem of using `total_results` without paging all results is that you cannot report the `application_id` label. And reporting this metric without that label is useless for me. A different approach will be listing all apps and then, for each app, list its events, but this will create more stress on the CC.

I've never been convinced of adding the `Application Events` metrics, there are few use cases for them, and storing `events` in prometheus is always challenging. As I said at #15, I'm thinking about removing it.

**Comment by frodenas** [comment]
I've removed the `Application Events` collector.
