### ISSUE TITLE
Set proper `useragent` in `http` call

### ISSUE THREAD

**Issue by janaurka** [cloudfoundry-community/cf_exporter#2]
Hey *

This is a `feature request`.

Can you please set a proper `useragent` in the `http` requests (for example: `Prometheus cf_exporter`) which will end up querying the Cloud-Controller?

We had some fun during a debugging session and we figured out that it often is pretty unclear which `service` does which `requests` since pretty much everything simply told us, that it’s a `go` application.

cheers
j

**Comment by frodenas** [comment]
This exporter uses the [go-cfclient](https://github.com/cloudfoundry-community/go-cfclient) library, which does NOT allow setting the `UserAgent`. So we need first to submit an issue at the go-cfclient github repo.

**Comment by frodenas** [comment]
This has been solved at [cf_exporter v0.2.1](https://github.com/cloudfoundry-community/cf_exporter/releases/tag/v0.2.1).
