### ISSUE TITLE
cf_exporter does not read out more than one org/space

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry-community/cf_exporter#3]
Hi,
I have configured the cf_exporter correctly, at least it is reading one organisation, one space and multiple applications. Now I have created more spaces and additional organisations, but I am still just able to see one org and one space respectively. 

When reading out `cf_space_info` in Prometheus I also just can see:
`cf_space_info{instance="localhost:9193",job="cf_exporter",space_id="c24f9f47-061c-49a6-ac27-c91a06ddacc5",space_name="development"}`

The interesting thing is though, when I deploy/delete applications in the existing org/space combination, the the change is visible instantly.

Any idea what I am doing wrong?

**Comment by frodenas** [comment]
@jhiemer Interesting, what `cf_exporter` version are you using? The one shipped with the prometheus bosh release?

**Comment by jhiemer** [comment]
@frodenas yes exactly 12.3.3.

**Comment by frodenas** [comment]
I don't know what might happen. We're using that version on different customers and the exporter is reporting all orgs/spaces.

How are you authenticating? Using a `client-id` or via a username/password?

**Comment by jhiemer** [comment]
The firehose exporter is configured via client_id/client_secret and the cf_exporter is configured via username/password. To make it even more interesting:

<img width="1658" alt="screen shot 2017-01-25 at 19 59 58" src="https://cloud.githubusercontent.com/assets/1557826/22304719/e468c7aa-e338-11e6-9aa9-c4dae4003ca0.png">

That shows the right number of Orgs/Spaces/Apps etc.

**Comment by frodenas** [comment]
@jhiemer I'm a bit confused now. That dashboard show the orgs/spaces from the `cf_exporter` (see the [cf_summary.json dashboard](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/src/cloudfoundry_dashboards/cf_summary.json#L324)), so where exactly did you see the discrepancy?

**Comment by jhiemer** [comment]
Yes you are correct, my initial description was unclear. When I look into the Dashboard `Apps: System` I see the discrepancy, with only 1 Org and 3 Applications. 
These values are coming from the firehose_nozzle, correct?

**Comment by frodenas** [comment]
The metrics come from the `firehose_exporter`, but if you're talking about the drop-down filters for the `org` and `space`, they come from the `cf_exporter`. 

In order to appear at the filters, there should be an app at that `org` and `space`, otherwise, they are not showed. Look at the [cf_apps_system.json](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/src/cloudfoundry_dashboards/cf_apps_system.json#L83) dashboard, it is using the `cf_application_info` metric (that come from the `cf_exporter`) and is using the `organization_name` label.

Maybe you have just created the `org` and `space` but they didn't have any `app` assigned yet. Can you please try to push an `app` and see if the `org` and `space` then appears?

**Comment by frodenas** [comment]
@jhiemer Did you see my previous comment? Have you checked if the newly created `org` and `space` has any `app`?

**Comment by jhiemer** [comment]
@frodenas yes still the same, deployed an application in Space, but it is not visible.

**Comment by jhiemer** [comment]
@frodenas coming back to this issue, I have tracked the cf_exporter now for a while and I can't see any errors. Is there any option for me to track down, why there so many information missing?

**Comment by shinji62** [comment]
Just to confirm, that I have more than 100 orgs and more than 300 spaces and I can see all of it.

**Comment by jhiemer** [comment]
@shinji62 ok then it seems to be a configuration issue on my side. Would you mind sharing your configuration of the client in your CF deployment? I even started to use the admin of CF, but still have the same problem.

**Comment by frodenas** [comment]
@jhiemer Ok, let's do some debugging:

1. Enable the `debug` level info at the `cf_exporter` job (manifest property `cf_exporter.log_level`). This will give us some info in case there's a problem.
2. Check the prometheus console (ip:9090) and at the graph, ran the query `cf_space_info`.
3. Add an `space` to your cf environment.
4. Repeat step 2. You should be able to see the new space. Be aware that prometheus must scrape the `cf_exporter` again, so it might take some minutes (depending on your prometheus configuration).
5. If step 4 doesn't show you the new `space`, ssh into the `cf_exporter` vm and check the logs at `/var/vcap/sys/log/cf_exporter/*.log`.

**Comment by frodenas** [comment]
@jhiemer I'm closing this issue, if you still have problems and can provide some debug info, then we can reopen it.
